name: GOV.UK Developer Documentation
subtitle: For developers on GOV.UK
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "lib", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlighter: rouge
baseurl: '/govuk-developers'
sass:
    sass_dir: css
