host: https://docs.publishing.service.gov.uk
service_link: /
enable_search: true

show_govuk_logo: true
service_name: Developer docs
full_service_name: GOV.UK Developer Documentation
description: Technical documentation for developers working on GOV.UK in GDS

# Suppress review banner in favour of bespoke 'Last updated' banner
show_review_banner: false

header_links:
  Dashboard: /
  Get started: /manual/get-started.html
  Apps: /apps.html
  Manual: /manual.html
  APIs: /apis.html
  Schemas: /content-schemas.html
  Document types: /document-types.html

footer_links:
  Accessibility: /accessibility.html

show_contribution_banner: true
github_repo: alphagov/govuk-developer-docs

redirects:
  /2nd-line/mirror-fallback.html: /manual/fall-back-to-mirror.html
  /apis/search-api.html: /apis/search/search-api.html
  /apps/content-performance-manager.html: /apps/content-data-api.html
  /dictionary.html: /manual/dictionary.html
  /getting-started.html: /manual/get-started.html
  /guides.html: /manual.html
  /manual/access-aws-console.html: /manual/get-started.html
  /manual/alerts/applications/sidekiq-monitoring.html: /manual/setting-up-new-sidekiq-monitoring-app.html
  /manual/alerts/email-alerts.html: /manual/alerts/email-alerts-travel-medical.html
  /manual/alerts/gor.html: /manual/alerts/goreplay.html
  /manual/alerts/process-file-handle-count-exceedes.html: /manual/alerts/process-file-handle-count-exceeds.html
  /manual/alerts/publisher-app-health-check-not-ok.html: /manual/alerts/publisher-app-healthcheck-not-ok.html
  /manual/alerts/data-sources-for-transition.html: /manual/transition-architecture.html
  /manual/alerts/rummager-queue-latency.html: /manual/alerts/search-api-queue-latency.html
  /manual/alerts/rummager-index-size-change.html: /manual/alerts/search-api-index-size-change.html
  /manual/alerts/whitehall-app-health-check-not-ok.html: /manual/alerts/whitehall-app-healthcheck-not-ok.html
  /manual/access-ci.html: /manual/access-jenkins.html
  /manual/archiving-and-redirecting-content.html: /manual/redirect-routes.html
  /manual/bouncer.html: /manual/transition-architecture.html
  /manual/create-a-concourse-pipeline.html: /manual/concourse.html
  /manual/create-a-new-open-source-project.html: /manual.html
  /manual/create-page.html: /manual/docs-style-guide.html
  /manual/creating-a-new-environment.html: /manual.html
  /manual/creating-pages.html: /manual/docs-style-guide.html
  /manual/data-gov-uk-backups.html: /manual/postgresql.html
  /manual/data-sources-for-transition.html: /manual/transition-architecture.html
  /manual/data-gov-uk-hacks.html: /manual/data-gov-uk-2nd-line.html
  /manual/elasticsearch.html: /manual/elasticsearch-dumps.html
  /manual/emergency-publishing-redis.html: /manual/emergency-publishing.html
  /manual/fastly-error-rate.html: /manual/alerts/fastly-error-rate.html
  /manual/fix-problems-with-vagrant.html: /manual.html
  /manual/gds-cli.html: /manual/access-aws-console.html
  /manual/howto-merge-a-pull-request-from-an-external-contributor.html: /manual/merge-pr.html
  /manual/howto-transition-a-site-to-govuk.html: /manual/transition-a-site.html
  /manual/intro-to-docker-even-more.html: /manual/how-govuk-docker-works.html
  /manual/manage-email-subscribers.html: /apis/email-alert-api/tasks.html
  /manual/migrate-testing-from-phantomjs-to-selenium-chrome.html: /manual.html
  /manual/mirror-fallback.html: /manual/fall-back-to-mirror.html
  /manual/nagios.html: /manual.html
  /manual/offsite-backup-and-restore.html: /manual/restore-from-offsite-backups.html
  /manual/deploying.html: /manual/development-pipeline.html
  /manual/redirecting-content-in-the-router.html: /manual/redirect-routes.html
  /manual/releasing-software.html: /manual/development-pipeline.html
  /manual/remove-redirected-url-from-transition.html: manual/remove-site-from-transition-tool.html
  /manual/renew_ssl_certificates.html: /manual/renew-a-tls-certificate.html
  /manual/setup-postgresql-replication.html: /manual/resync-postgres-standby.html
  /manual/set-up-aws-account.html: /manual/get-started.html
  /manual/setting-up-new-sidekiq-monitoring-app.html: /manual/sidekiq.html
  /manual/rummager-traffic-replay.html: /manual/search-api-traffic-replay.html
  /manual/technical-setup.html: /manual/on-call.html
  /manual/testing.html: https://gds-way.cloudapps.digital/manuals/programming-languages/ruby.html
  /manual/troubleshooting-vagrant.html: /manual/fix-problems-with-vagrant.html
  /manual/upgrade-to-sentry.html: /manual/sentry.html
  /manual/use-terraboard-to-monitor-terraform-state.html: /manual.html
  /manual/user-management-in-aws.html: /manual/get-started.html
  /manual/virus-scanning.html: /manual/alerts/virus-scanning.html
  /manual/whitelist-site-in-transition.html: /manual/allowlist-site-in-transition.html
  /opsmanual.html: /manual.html
  /opsmanual/ab_testing.html: /manual/ab-testing.html
  /opsmanual/content-preview.html: /manual/content-preview.html
  /opsmanual/dictionary.html: /manual/dictionary.html
  /opsmanual/emergency-publishing.html: /manual/emergency-publishing.html
  /opsmanual/github.html: /manual/github.html
  /opsmanual/keeping-software-current.html: /manual/keeping-software-current.html
  /opsmanual/kibana.html: /manual/kibana.html
  /opsmanual/screens.html: /manual/screens.html
  /opsmanual/taxonomy.html: /manual/taxonomy.html
