host: https://docs.publishing.service.gov.uk
service_link: /

show_govuk_logo: true
service_name: Developer docs
full_service_name: GOV.UK Developer Documentation
description: Technical documentation for developers working on GOV.UK in GDS

header_links:
  Dashboard: /
  Get started: /manual/get-started.html
  Apps: /apps.html
  Manual: /manual.html
  APIs: /apis.html
  Schemas: /content-schemas.html
  Document types: /document-types.html

ga_tracking_id: UA-91585274-1

show_contribution_banner: true
github_repo: alphagov/govuk-developer-docs
