host: https://docs.publishing.service.gov.uk
service_link: /
enable_search: true

show_govuk_logo: true
service_name: Developer docs
full_service_name: GOV.UK Developer Documentation
description: Technical documentation for developers working on GOV.UK in GDS

# Suppress review banner in favour of bespoke 'Last updated' banner
show_review_banner: false

header_links:
  Get started: /manual/get-started.html
  Manual: /manual.html
  Kubernetes: /kubernetes/
  Apps: /apps.html
  Repos: /repos.html
  Schemas: /content-schemas.html
  Document types: /document-types.html

footer_links:
  Accessibility: /accessibility.html
  Cookies: /cookies.html

show_contribution_banner: true
github_repo: alphagov/govuk-developer-docs

redirects:
  /2nd-line/mirror-fallback.html: /manual/fall-back-to-mirror.html
  /apis.html: /apps.html
  /apis/email-alert-api/analytics.html: /apps/email-alert-api/analytics.html
  /apis/email-alert-api/api.html: /apps/email-alert-api/api.html
  /apis/email-alert-api/data-cleanup-mechanisms.html: /apps/email-alert-api/data-cleanup-mechanisms.html
  /apis/email-alert-api/env-vars.html: /apps/email-alert-api/env-vars.html
  /apis/email-alert-api/matching-content-to-subscriber-lists.html: /apps/email-alert-api/matching-content-to-subscriber-lists.html
  /apis/email-alert-api/support-tasks.html: /apps/email-alert-api/support-tasks.html
  /apis/link-checker-api/api.html: /apps/link-checker-api/api.html
  /apis/link-checker-api/blitz.html: /apps/link-checker-api/blitz.html
  /apis/publishing-api/admin-tasks.html: /apps/publishing-api/admin-tasks.html
  /apis/publishing-api/api.html: /apps/publishing-api/api.html
  /apis/publishing-api/dependency-resolution.html: /apps/publishing-api/dependency-resolution.html
  /apis/publishing-api/link-expansion.html: /apps/publishing-api/link-expansion.html
  /apis/publishing-api/model.html: /apps/publishing-api/model.html
  /apis/publishing-api/pact_testing.html: /apps/publishing-api/pact_testing.html
  /apis/publishing-api/publishing-application-examples.html: /apps/publishing-api/publishing-application-examples.html
  /apis/publishing-api/rabbitmq.html: /apps/publishing-api/amazonmq.html
  /apis/search-api.html: /apps/search-api.html
  /apis/search-api/adding-new-fields.html: /apps/search-api/adding-new-fields.html
  /apis/search-api/content-api.html: /apps/search-api/content-api.html
  /apis/search-api/content_overview.html: /apps/search-api/content_overview.html
  /apis/search-api/documents.html: /apps/search-api/documents.html
  /apis/search-api/how-search-works.html: /apps/search-api/how-search-works.html
  /apis/search-api/indexing.html: /apps/search-api/indexing.html
  /apis/search-api/learning-to-rank.html: /apps/search-api/learning-to-rank.html
  /apis/search-api/new-indexing-process.html: /apps/search-api/new-indexing-process.html
  /apis/search-api/popularity.html: /apps/search-api/popularity.html
  /apis/search-api/publishing-finders.html: /apps/search-api/publishing-finders.html
  /apis/search-api/relevancy.html: /apps/search-api/relevancy.html
  /apis/search-api/schemas.html: /apps/search-api/schemas.html
  /apis/search-api/search-api.html: /apps/search-api/search-api.html
  /apis/search-api/search-quality-metrics.html: /apps/search-api/search-quality-metrics.html
  /apis/search/search-api.html: /apps/search-api.html
  /apis/whitehall/api.html: /apps/whitehall/api.html
  /apis/whitehall/css.html: /apps/whitehall/css.html
  /apis/whitehall/edition_workflow.html: /apps/whitehall/edition_workflow.html
  /apis/whitehall/finders.html: /apps/whitehall/finders.html
  /apis/whitehall/internationalisation_guide.html: /apps/whitehall/internationalisation_guide.html
  /apis/whitehall/javascript.html: /apps/whitehall/javascript.html
  /apis/whitehall/link_checker_api_integration.html: /apps/whitehall/link_checker_api_integration.html
  /apis/whitehall/search_setup_guide.html: /apps/whitehall/search_setup_guide.html
  /apis/whitehall/testing_guide.html: /apps/whitehall/testing_guide.html
  /apis/whitehall/timestamps.html: /apps/whitehall/timestamps.html
  /apps/account-api.html: /repos/account-api.html
  /apps/asset-manager.html: /repos/asset-manager.html
  /apps/authenticating-proxy.html: /repos/authenticating-proxy.html
  /apps/bouncer.html: /repos/bouncer.html
  /apps/business-support-api.html: /repos/business-support-api.html
  /apps/business-support-finder.html: /repos/business-support-finder.html
  /apps/by-team.html: /apps.html
  /apps/calculators.html: /repos/calculators.html
  /apps/calendars.html: /repos/calendars.html
  /apps/ckan-functional-tests.html: /repos/ckan-functional-tests.html
  /apps/ckanext-datagovuk.html: /repos/ckanext-datagovuk.html
  /apps/collections.html: /repos/collections.html
  /apps/collections-publisher.html: /repos/collections-publisher.html
  /apps/contacts-admin.html: /repos/contacts-admin.html
  /apps/contacts-frontend.html: /repos/contacts-frontend.html
  /apps/content-data-admin.html: /repos/content-data-admin.html
  /apps/content-data-api.html: /repos/content-data-api.html
  /apps/content-performance-manager.html: /repos/content-data-api.html
  /apps/content-publisher.html: /repos/content-publisher.html
  /apps/content-store.html: /repos/content-store.html
  /apps/content-tagger.html: /repos/content-tagger.html
  /apps/datagovuk-tech-docs.html: /repos/datagovuk-tech-docs.html
  /apps/datagovuk_find.html: /repos/datagovuk_find.html
  /apps/datagovuk_publish.html: /repos/datagovuk_publish.html
  /apps/datagovuk_publish_queue_monitor.html: /repos/datagovuk_publish_queue_monitor.html
  /apps/datagovuk_reference.html: /repos/datagovuk_reference.html
  /apps/design-principles.html: /repos/design-principles.html
  /apps/eligibility-viewer.html: /repos/eligibility-viewer.html
  /apps/email-alert-api.html: /repos/email-alert-api.html
  /apps/email-alert-frontend.html: /repos/email-alert-frontend.html
  /apps/email-alert-service.html: /repos/email-alert-service.html
  /apps/feedback.html: /repos/feedback.html
  /apps/finder-frontend.html: /repos/finder-frontend.html
  /apps/frontend.html: /repos/frontend.html
  /apps/gds-api-adapters.html: /repos/gds-api-adapters.html
  /apps/government-frontend.html: /repos/government-frontend.html
  /apps/govuk-content-store-examples.html: /repos/govuk-content-store-examples.html
  /apps/govuk-delivery.html: /repos/govuk-delivery.html
  /apps/govuk-display-screen.html: /repos/govuk-display-screen.html
  /apps/govuk-docker.html: /repos/govuk-docker.html
  /apps/govuk-load-testing.html: /repos/govuk-load-testing.html
  /apps/govuk-pact-broker.html: /repos/govuk-pact-broker.html
  /apps/govuk-related-links-recommender.html: /repos/govuk-related-links-recommender.html
  /apps/govuk-secondline-blinken.html: /repos/govuk-secondline-blinken.html
  /apps/govuk-user-intent-survey-explorer.html: /repos/govuk-user-intent-survey-explorer.html
  /apps/govuk-user-journey-models.html: /repos/govuk-user-journey-models.html
  /apps/govuk-zendesk-display-screen.html: /repos/govuk-zendesk-display-screen.html
  /apps/govuk_app_config.html: /repos/govuk_app_config.html
  /apps/govuk_content_api.html: /repos/govuk_content_api.html
  /apps/govuk_need_api.html: /repos/govuk_need_api.html
  /apps/govuk_schemas.html: /repos/govuk_schemas.html
  /apps/hmrc-manuals-api.html: /repos/hmrc-manuals-api.html
  /apps/imminence.html: /repos/imminence.html
  /apps/licence-finder.html: /repos/licence-finder.html
  /apps/licensify.html: /repos/licensify.html
  /apps/licensify-admin.html: /repos/licensify-admin.html
  /apps/licensify-feed.html: /repos/licensify-feed.html
  /apps/link-checker-api.html: /repos/link-checker-api.html
  /apps/local-links-manager.html: /repos/local-links-manager.html
  /apps/locations-api.html: /repos/locations-api.html
  /apps/manuals-publisher.html: /repos/manuals-publisher.html
  /apps/maslow.html: /repos/maslow.html
  /apps/metadata-api.html: /repos/metadata-api.html
  /apps/multipage-frontend.html: /repos/multipage-frontend.html
  /apps/organisations-publisher.html: /repos/organisations-publisher.html
  /apps/panopticon.html: /repos/panopticon.html
  /apps/policy-publisher.html: /repos/policy-publisher.html
  /apps/publisher.html: /repos/publisher.html
  /apps/publishing-api.html: /repos/publishing-api.html
  /apps/publishing-api/rabbitmq.html: /apps/publishing-api/amazonmq.html
  /apps/release.html: /repos/release.html
  /apps/router.html: /repos/router.html
  /apps/router-api.html: /repos/router-api.html
  /apps/seal.html: /repos/seal.html
  /apps/search-admin.html: /repos/search-admin.html
  /apps/search-analytics.html: /repos/search-analytics.html
  /apps/search-api.html: /repos/search-api.html
  /apps/search-performance-explorer.html: /repos/search-performance-explorer.html
  /apps/service-manual-publisher.html: /repos/service-manual-publisher.html
  /apps/short-url-manager.html: /repos/short-url-manager.html
  /apps/side-by-side-browser.html: /repos/side-by-side-browser.html
  /apps/signon.html: /repos/signon.html
  /apps/slimmer.html: /repos/slimmer.html
  /apps/smart-answers.html: /repos/smart-answers.html
  /apps/special-route-publisher.html: /repos/special-route-publisher.html
  /apps/specialist-frontend.html: /repos/specialist-frontend.html
  /apps/specialist-publisher.html: /repos/specialist-publisher.html
  /apps/static.html: /repos/static.html
  /apps/support.html: /repos/support.html
  /apps/support-api.html: /repos/support-api.html
  /apps/transition.html: /repos/transition.html
  /apps/travel-advice-publisher.html: /repos/travel-advice-publisher.html
  /apps/whitehall.html: /repos/whitehall.html
  /dictionary.html: /manual/dictionary.html
  /getting-started.html: /manual/get-started.html
  /guides.html: /manual.html
  /manual/access-aws-console.html: /manual/get-started.html
  /manual/add-a-pingdom-check.html: /manual/pingdom.html
  /manual/alerts/applications/sidekiq-monitoring.html: /manual/setting-up-new-sidekiq-monitoring-app.html
  /manual/alerts/data-sources-for-transition.html: /manual/transition-architecture.html
  /manual/alerts/data-sync.html: /manual/govuk-env-sync.html
  /manual/alerts/email-alerts.html: /manual/alerts/email-alerts-travel-medical.html
  /manual/alerts/process-file-handle-count-exceedes.html: /manual/alerts/process-file-handle-count-exceeds.html
  /manual/alerts/publisher-app-health-check-not-ok.html: /manual/alerts/publisher-app-healthcheck-not-ok.html
  /manual/alerts/rabbitmq-no-consumers-listening.html: /manual/alerts/amazonmq-no-consumers-listening.html
  /manual/alerts/rummager-index-size-change.html: /manual/alerts/search-api-index-size-change.html
  /manual/alerts/rummager-queue-latency.html: /manual/alerts/search-api-queue-latency.html
  /manual/alerts/whitehall-app-health-check-not-ok.html: /manual/alerts/whitehall-app-healthcheck-not-ok.html
  /manual/archiving-and-redirecting-content.html: /manual/redirect-routes.html
  /manual/bouncer.html: /manual/transition-architecture.html
  /manual/bulk-email.html: /apps/email-alert-api/bulk-email.html
  /manual/configure-github-repo.html: /manual/github.html
  /manual/create-a-new-open-source-project.html: /manual.html
  /manual/create-page.html: /manual/docs-style-guide.html
  /manual/creating-a-new-environment.html: /manual.html
  /manual/creating-pages.html: /manual/docs-style-guide.html
  /manual/data-gov-uk-backups.html: /manual/postgresql.html
  /manual/data-gov-uk-hacks.html: /manual/data-gov-uk-2nd-line.html
  /manual/data-gov-uk-map-previews.html: /manual/data-gov-uk-2nd-line.html
  /manual/data-gov-uk-monitoring.html: /manual/data-gov-uk-2nd-line.html
  /manual/data-gov-uk-operations.html.md: /manual/data-gov-uk-2nd-line.html
  /manual/data-gov-uk-supporting-ckan.html: /manual/data-gov-uk-2nd-line.html
  /manual/data-sources-for-transition.html: /manual/transition-architecture.html
  /manual/deploying.html: /manual/development-pipeline.html
  /manual/elasticsearch.html: /manual/elasticsearch-dumps.html
  /manual/emergency-publishing-redis.html: /manual/emergency-publishing.html
  /manual/error-reporting.html: /manual/sentry.html
  /manual/fastly-error-rate.html: /manual/alerts/fastly-error-rate.html
  /manual/fix-problems-with-vagrant.html: /manual.html
  /manual/gds-cli.html: /manual/access-aws-console.html
  /manual/github-access.html: /manual/github.html
  /manual/give-a-content-designer-access-to-github.html: /manual/github.html
  /manual/howto-manually-remove-assets.html: /manual/manage-assets.html
  /manual/howto-merge-a-pull-request-from-an-external-contributor.html: /manual/merge-pr.html
  /manual/howto-replace-an-assets-file.html: /manual/manage-assets.html
  /manual/howto-remove-change-note-from-whitehall.html: /manual/howto-remove-change-note.html
  /manual/howto-transition-a-site-to-govuk.html: /manual/transition-a-site.html
  /manual/howto-upload-an-asset-to-asset-manager.html: /manual/manage-assets.html
  /manual/intro-to-docker-even-more.html: /manual/how-govuk-docker-works.html
  /manual/kubernetes-infrastructure.html: /manual/kubernetes/cheatsheet.html
  /manual/load-test-email-alert-api.html: /apps/email-alert-api/load-test-email-alert-api.html
  /manual/manage-email-subscribers.html: /apps/email-alert-api/tasks.html
  /manual/manage-ruby-dependencies.html: /manual/manage-dependencies.html
  /manual/migrate-testing-from-phantomjs-to-selenium-chrome.html: /manual.html
  /manual/mirror-fallback.html: /manual/fall-back-to-mirror.html
  /manual/nagios.html: /manual.html
  /manual/pact-broker.html: /manual/pact-testing.html
  /manual/receiving-emails-from-email-alert-api-in-integration-and-staging.html: /apps/email-alert-api/receiving-emails-from-email-alert-api-in-integration-and-staging.html
  /manual/redirecting-content-in-the-router.html: /manual/redirect-routes.html
  /manual/releasing-software.html: /manual/development-pipeline.html
  /manual/remove-redirected-url-from-transition.html: manual/remove-site-from-transition-tool.html
  /manual/renew_ssl_certificates.html: /manual/renew-a-tls-certificate.html
  /manual/repository-mirroring.html: /manual/github-unavailable.html
  /manual/rummager-traffic-replay.html: /manual/search-api-traffic-replay.html
  /manual/scale-unicorn-workers.html: /kubernetes/manage-app/scale-app/
  /manual/set-up-aws-account.html: /manual/get-started.html
  /manual/set-up-gcp-account.html: /manual/google-cloud-platform-gcp.html
  /manual/setting-up-new-sidekiq-monitoring-app.html: /manual/sidekiq.html
  /manual/technical-setup.html: /manual/on-call.html
  /manual/troubleshooting-vagrant.html: /manual/fix-problems-with-vagrant.html
  /manual/upgrade-to-sentry.html: /manual/sentry.html
  /manual/upload-asset-to-whitehall.html: /manual/manage-assets.html
  /manual/use-terraboard-to-monitor-terraform-state.html: /manual.html
  /manual/user-management-in-aws.html: /manual/get-started.html
  /manual/virus-scanning.html: /manual/alerts/virus-scanning.html
  /manual/welcome-to-2nd-line.html: /manual/2nd-line.html
  /manual/whitelist-site-in-transition.html: /manual/allowlist-site-in-transition.html
  /opsmanual.html: /manual.html
  /opsmanual/ab_testing.html: /manual/ab-testing.html
  /opsmanual/content-preview.html: /manual/content-preview.html
  /opsmanual/dictionary.html: /manual/dictionary.html
  /opsmanual/emergency-publishing.html: /manual/emergency-publishing.html
  /opsmanual/github.html: /manual/github.html
  /opsmanual/keeping-software-current.html: /manual/keeping-software-current.html
  /opsmanual/kibana.html: /manual/kibana.html
  /opsmanual/screens.html: /manual/screens.html
  /opsmanual/taxonomy.html: /manual/taxonomy.html
